----exec [dbo].[SP_LoanReport] '2020-01-31'

CREATE PROC [dbo].[SP_LoanReport]
	@REPORT_DT DATE
AS

DECLARE  @EOM_DT DATE = EOMONTH(@REPORT_DT)

BEGIN
	SET NOCOUNT ON;


DECLARE @accumurappraisal TABLE
(
	ACC_NO nvarchar(50),
	BRANCH_CODE nvarchar(50),
	COLLATERAL_ID nvarchar(50),
	REPORT_DATE datetime,
	APPRAISAL_AGE datetime,
	EXTERNAL_OR_INTERNAL nvarchar(20),
	DIFFERENCIAL_REPORT_DATE int
)

insert into @accumurappraisal
SELECT
	NAK.account_no,
	NAK.branch_code,
	NAK.COLLATERAL_ID,
	NAK.REPORT_DATE,
	convert(date,(case when NAK.DATE1 < NAK.DATE2 then NAK.DATE2 else  NAK.DATE1 end), 112),
	case 
	when NAK.DATE1 < NAK.DATE2 
		then 'EXTERNAL' -- INDEPENDENT
		else  'INTERNAL' -- NON INDEPENDENT
	end,
	ABS(DATEDIFF(month,@report_dt,convert(date,(case when NAK.DATE1 < NAK.DATE2 then NAK.DATE2 else  NAK.DATE1 end), 112)))	
FROM COLLATERAL NAK
WHERE NAK.REPORT_DATE  = @REPORT_DT

DECLARE @Loan TABLE (
	[REPORT_DT] [date] NULL,
	[BRANCH] [varchar](10) NULL,
	[RG_BRANCH] [varchar](10) NULL,
	[ID_OPRSNL] [varchar](50) NULL,
	ACCOUNT_NO [varchar](25) NULL,
	[COLLATERAL_NO] [varchar](25) NULL,
	[ID_DBTUR] [varchar](20) NULL,
	[CHARACTER] [varchar](20) NULL,
	[INITIAL_AGREEMENT_NO] [varchar](50) NULL,
	[INITIAL_AGREEMENT_DATE][date] NULL,
	[LAST_AGREEMENT_NO][varchar](50) NULL,
	[LAST__AGREEMENT_DATE][date] NULL,
	[NITIAL_DATE] [date] NULL,
	[START_DATE] [date] NULL,
	[LAST_DATE] [date] NULL,
	[DEBTOR_CATEGORY] [varchar](50) NULL,
	[PORTOFOLIO_CATEGORY] [varchar](50) NULL,
	[CHARACTER2] [varchar](50) NULL,
	CREDIT_ORIENTATION [varchar](50) NULL,
	CURRENCY [varchar](50) NULL,
	CLASSIFICATION_ASSET [varchar](50) NULL,
	CREDIT_DESC [varchar](50) NULL,
	SECTOR_CREDIT[varchar](50) NULL,
	ECONOMY_SECTOR[varchar](50) NULL,
	PROJECT_LOCATION[varchar](50) NULL,
	MAIN_RATE_DESC[varchar](50) NULL,
	MAIN_RATE [float] NULL,
	QUALITY [varchar](50) NULL,
	MAIN_PLAFOND [decimal](32, 2) NULL,
	PLAFOND [decimal](32, 2) NULL,
	TOTAL_DBT [decimal](32, 2) NULL,
	DEBIT_MOVEMENT [decimal](32, 2) NULL,
	FACILITY_IN_RATE [decimal](32, 2) NULL,
	COLLATERAL_AMOUNT_RESULT [decimal](32, 2) NULL,
	COMMITED_IDR [decimal](32, 2) NULL,
	UNUSED_IDR [decimal](32, 2) NULL,
	COLLATERAL_AMOUNT_RESULT  [decimal](32, 2) NULL,
	[CREDIT_RESULT] [decimal](32, 2) NULL,
	[LENIENCY_RESULT] [decimal](32, 2) NULL,
)

insert into @Loan
SELECT 
		REPORT_DT,			
[BRANCH],
	[RG_BRANCH],
	[ID_OPRSNL],
	ACCOUNT_NO,
	[COLLATERAL_NO],
	[ID_DBTUR],
	[CHARACTER],
	[INITIAL_AGREEMENT_NO],
	[INITIAL_AGREEMENT_DATE],
	[LAST_AGREEMENT_NO],
	[LAST__AGREEMENT_DATE],
	[NITIAL_DATE],
	[START_DATE],
	[LAST_DATE],
	[DEBTOR_CATEGORY],
	[PORTOFOLIO_CATEGORY],
	[CHARACTER2],
	CREDIT_ORIENTATION,
	CURRENCY,
	CLASSIFICATION_ASSET,
	CREDIT_DESC,
	SECTOR_CREDIT,
	ECONOMY_SECTOR,
	PROJECT_LOCATION,
	MAIN_RATE_DESC,
	cast(MAIN_RATE as decimal(10,2)) as MAIN_RATE,
	QUALITY,
	MAIN_PLAFOND,
	PLAFOND,
	TOTAL_DBT,
	DEBIT_MOVEMENT,
	FACILITY_IN_RATE,
	COLLATERAL_AMOUNT_RESULT,
	COMMITED_IDR,
	UNUSED_IDR,
	COLLATERAL_AMOUNT_RESULT,
	[CREDIT_RESULT],
	[LENIENCY_RESULT]		
	REPLACE(REPLACE(REPLACE(COLLATERAL_NO,'.',''),'-',''),' ','') AS COLLATERAL_NO,
	


	  CASE
		WHEN ISNULL(Limit_Amount_IDR,0) <= 10000000000
	  THEN ISNULL(COLLATERAL_AMOUNT,0)
	   ELSE ISNULL(IND_AMOUNT,0)
	   END as COLLATERAL_AMOUNT_RESULT,

		ISNULL( try_convert (decimal(24, 0), 
			CASE WHEN COL.COLLATERAL_ID IS NULL THEN
				(
					case when ISNULL(Limit_Amount_IDR,0) <= 10000000000 
						THEN (COLLATERAL_AMOUNT * (CREDIT_RESULT/100))
					ELSE 
						(IND_AMOUNT * (CREDIT_RESULT/100))
					END
				)
			ELSE
				(
					CASE WHEN ISNULL(IND_AMOUNT,0) = 0 THEN 
						COLLATERAL_AMOUNT * (CREDIT_RESULT/100) 
					ELSE 
						IND_AMOUNT * (CREDIT_RESULT/100)
					END
				)
			END
		) , 0 )as 'CREDIT_RESULT',


		ISNULL( try_convert( decimal(24,0), 
			CASE WHEN COL.COLLATERAL_ID IS NULL THEN
				(
					case when ISNULL(Limit_Amount_IDR,0) <= 10000000000 
						THEN COLLATERAL_AMOUNT - (COLLATERAL_AMOUNT * (CREDIT_RESULT/100))
					ELSE 
						ISNULL(IND_AMOUNT,0) - (IND_AMOUNT * (CREDIT_RESULT/100))
					END
				)
			ELSE
				(
					CASE WHEN ISNULL(IND_AMOUNT,0) = 0 THEN 
						ISNULL(COLLATERAL_AMOUNT,0) - COLLATERAL_AMOUNT * (CREDIT_RESULT/100) 
					ELSE 
						IND_AMOUNT - IND_AMOUNT * (CREDIT_RESULT/100)
					END
				)
			END
			) , 0 ) as 'LENIENCY_RESULT',	
		

FROM (
	SELECT
		NAK.COLLATERAL_AMOUNT as [COLLATERAL_AMOUNT],
		NAK.IND_AMOUNT as [IND_AMOUNT],
		NAK.COLLATERAL_ID as COLLATERAL_NO,
		NAK.COLLATERAL_CODE AS COLCOD,
		NAK.EQUITY_PARTICIPATION AS EQU,
		NAK.DATE1 AS DATE1,
		NAK.DATE2 AS DATE2,
		CL.Limit_Amount_IDR AS [Limit_Amount_IDR],
		@REPORT_DT AS [REPORT_DT],
		LN.BRANCH_CODE AS [BRANCH],
		nAK.CHARACTERISTIC AS KARAKTER,
		BR.REGULATOR_BRANCH_CD AS [RG_BRANCH],
		'1' AS ID_OPRSNL,
		LN.ACCOUNT_NO AS ACCOUNT_NO,
		LN.CUSTOMER_ID AS [ID_DBTUR],
		LN.CHARACTER AS [CHARACTER],
		LN.INITIAL_AGREE_NUMBER AS [INITIAL_AGREEMENT_NO],
		CONVERT(DATE, CAST(CASE WHEN LN.INITIAL_AGREE_DATE = 0 THEN null ELSE LN.INITIAL_AGREE_DATE END AS VARCHAR), 112)  AS [INITIAL_AGREEMENT_DATE],
		LN.LAST_AGREE_NUMBER AS [NO_AKAD_AKHR],
		CONVERT(DATE, CAST(CASE WHEN LN.LAST_AGREEMENT_DATE = 0 THEN null ELSE LN.LAST_AGREEMENT_DATE END AS VARCHAR), 112)  AS [LAST_AGREEMENT_DATE],
		CONVERT(DATE, CAST(CASE WHEN LN.ISSUE_DATE = 0 THEN null ELSE LN.ISSUE_DATE END AS VARCHAR), 112)  AS [INITIAL_DATE],
		CONVERT(DATE, CAST(CASE WHEN LN.START_DATE = 0 THEN null ELSE LN.START_DATE END AS VARCHAR), 112)  AS [START_DATE],
		CONVERT(DATE, CAST(CASE WHEN LN.MATURITY_DATE = 0 THEN null ELSE LN.MATURITY_DATE END AS VARCHAR), 112)  AS [LAST_DATE],
		LN.DEBTOR_CATEGORY AS [DEBTOR_CATEGORY],
		LN.PORTOFOLIO_CATEGORY. AS [PORTOFOLIO_CATEGORY],
		LN.CHARACTER2 AS [CHARACTER2],
		LN.PROJECT_ORIENTATION AS [PROJECT_ORIENTATION],
		LN.CURRENCY AS CURRENCY,
		LN.CLASSIFICATION AS CLASSIFICATION_ASSET,
		LN.CREDIT_DESC AS CREDIT_DESC,
		NULL AS SECTOR_CREDIT,
		LN.ECONOMY_SECTOR, AS ECONOMY_SECTOR,
		LN.PROJECT_LOCATION AS [PROJECT_LOCATION],
		LN.MAIN_RATE_DESC AS [MAIN_RATE_DESC],
		CAST(LN.FACILITY_INT_RATE AS DECIMAL(10,2)) AS MAIN_RATE,
		LN.CLASSIFICATION_CREDIT AS QUALITY,
		LN.MAIN_PLAFONDD_IDR AS MAIN_PLAFOND,
	    ROUND(ABS(L.PLAFOND_ACTUAL * FR.Currency_Rate),0,1) AS PLAFOND,
		LN.NOMINAL_IDR  AS TOTAL_DBT,
		ROUND(ABS(CASE WHEN LN.FASILITY_CURRENCY = FR.Currency_Mnemonic AND LN.FASILITY_CURRENCY ='USD' THEN LN.DEBIT_MOVEMENT_IDR
				ELSE LN.DEBIT_MOVEMENT_ORI * FR.Currency_Rate END),0,1) AS DEBT_MOVEMENT,
     	LN.INTEREST_ACCRUED1 AS FACILITY_IN_RATE, 
		LN.NOMINAL_ORI_AMOUNT AS COLLATERAL_AMOUNT_RESULT,
		0 AS COMMITED_IDR,
		case when LN.NOMINAL_IDR > LN.PLAFOND_IDR THEN '0'  ELSE LN.UNUSED_FACILITY_IDR END AS UNUSED_IDR,	
		cast(
		case when NAK.CHARACTERISTIC= '1' and  NAK.COLLATERAL_CODE not in ('042','043','047','048','086','087') then 100
			when NAK.CHARACTERISTIC  = '1' and NAK.COLLATERAL_CODE in ('042','043','047','048','086','087') and NAK.EQUITY_PARTICIPATION = '02' then 50
			when -- start formula 3
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO 
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) <= 12
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('161','162','163','164','175','187','190','191','192') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '01' 
				then 70
			when
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO 
								and NAK.BRANCH_CODE = a.BRANCH_CODE 
								and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
								and NAK.REPORT_DATE = a.REPORT_DATE) between 13 and 18
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('161','162','163','164','175','187','190','191','192') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '01' 
				then 50
			when
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO 
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) between 19 and 24
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('161','162','163','164','175','187','190','191','192') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '01' 
				then 30
			when -- end formula 3
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO 
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) > 24
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('161','162','163','164','175','187','190','191','192') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '01' 
				then 50
			when -- start formula 4	
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO 
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) <= 12
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('189','193') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '03' 
				then 70
			when 
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO 
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) between 13 and 18
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('189','193') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '03' 
				then 50
			when 
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO 
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) between 19 and 24
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('189','193') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '03' 
				then 50
			when -- end formula 4 
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO 
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) > 24
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('189','193') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '03' 
				then 0
			when -- start formula 5
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO 
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) <= 18
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('176','177') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '01' 
				and (select EXTERNAL_OR_INTERNAL 
							from @accumurappraisal a 
								where	LN.ACCOUNT_NO = a.ACC_NO	
									and NAK.BRANCH_CODE = a.BRANCH_CODE 
									and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
									and NAK.REPORT_DATE = a.REPORT_DATE) = 'EKSTERNAL'
				then 70
			when 
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO	
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) between 19 and 24
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('176','177') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '01' 
				and (select EXTERNAL_OR_INTERNAL 
						from @accumurappraisal a 
							where	LN.ACCOUNT_NO = a.ACC_NO	
								and NAK.BRANCH_CODE = a.BRANCH_CODE 
								and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
								and NAK.REPORT_DATE = a.REPORT_DATE) = 'EKSTERNAL'
				then 50
			when 
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO	
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) between 25 and 30
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('176','177') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '01' 
				and (select EXTERNAL_OR_INTERNAL 
						from @accumurappraisal a 
							where	LN.ACCOUNT_NO = a.ACC_NO	
								and NAK.BRANCH_CODE = a.BRANCH_CODE 
								and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
								and NAK.REPORT_DATE = a.REPORT_DATE) = 'EKSTERNAL'
				then 50
			when -- end formula 5
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO	
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) > 30
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('176','177') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '01' 
				and (select EXTERNAL_OR_INTERNAL 
						from @accumurappraisal a 
							where	LN.ACCOUNT_NO = a.ACC_NO	
								and NAK.BRANCH_CODE = a.BRANCH_CODE 
								and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
								and NAK.REPORT_DATE = a.REPORT_DATE) = 'EKSTERNAL'
				then 0
			when -- start formula 6	
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO	
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) <= 12
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('176','177') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '01' 
				and (select EXTERNAL_OR_INTERNAL 
						from @accumurappraisal a 
							where	LN.ACCOUNT_NO = a.ACC_NO	
								and NAK.BRANCH_CODE = a.BRANCH_CODE 
								and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
								and NAK.REPORT_DATE = a.REPORT_DATE) = 'INTERNAL'
				then 70
			when 
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO	
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) between 13 and 18
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('176','177')
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '01' 
				and (select EXTERNAL_OR_INTERNAL 
						from @accumurappraisal a 
							where	LN.ACCOUNT_NO = a.ACC_NO	
								and NAK.BRANCH_CODE = a.BRANCH_CODE 
								and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
								and NAK.REPORT_DATE = a.REPORT_DATE) = 'INTERNAL'
				then 50
			when 
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO	
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) between 19 and 24
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('176','177') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '01' 
				and (select EXTERNAL_OR_INTERNAL 
						from @accumurappraisal a 
							where	LN.ACCOUNT_NO = a.ACC_NO	
								and NAK.BRANCH_CODE = a.BRANCH_CODE 
								and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
								and NAK.REPORT_DATE = a.REPORT_DATE) = 'INTERNAL'
				then 50
			when -- end formula 6 
				(select DIFFERENCIAL_REPORT_DATE 
					from @accumurappraisal a 
						where	LN.ACCOUNT_NO = a.ACC_NO	
							and NAK.BRANCH_CODE = a.BRANCH_CODE 
							and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
							and NAK.REPORT_DATE = a.REPORT_DATE) > 24
				and NAK.CHARACTERISTIC = '2' 
				and NAK.COLLATERAL_CODE in ('176','177') 
				and ln.CLASSIFICATION <> '1' 
				and NAK.EQUITY_PARTICIPATION = '01' 
				and (select EXTERNAL_OR_INTERNAL 
						from @accumurappraisal a 
							where	LN.ACCOUNT_NO = a.ACC_NO 
								and NAK.BRANCH_CODE = a.BRANCH_CODE 
								and NAK.COLLATERAL_ID = a.COLLATERAL_ID 
								and NAK.REPORT_DATE = a.REPORT_DATE) = 'INTERNAL'
				then 0
			else 0
			end as decimal(9,6)) AS [CREDIT_RESULT],
			NULL AS [LENIENCY_RESULT],
			NAK.COLLATERAL_ID
	FROM STAGING.[dbo].LOAN LN 
	LEFT JOIN COLLATERAL NAK
		ON NAK.ACCOUNT_NO = LN.ACCOUNT_NO  and NAK.REPORT_DATE = LN.REPORT_DATE
		LEFT JOIN STAGING.[dbo].LENDING L
	    ON LN.ACCOUNT_NO = L.ACCOUNT_NO
		AND LN.CUSTOMER_ID = L.CIF
		AND  LN.REPORT_DATE = L.REPORT_DATE
	LEFT JOIN STAGING.[DBO].[F_RR_CURRENCY] FR
		ON FR.Currency_Mnemonic = LN.FASILITY_CURRENCY 
		AND  FR.REPORT_DATE = LN.REPORT_DATE
	LEFT JOIN STAGING.[dbo].CUSTOMER_LIMIT CL
	    ON CL.CIF = NAK.CUSTOMER_ID AND  NAK.REPORT_DATE = CL.REPORT_DATE
	WHERE LN.REPORT_DATE  = @REPORT_DT
		AND LN.ACCOUNT_STATUS = 'A'
) RESULT
LEFT JOIN (
	SELECT COLLATERAL_ID 
		FROM (
			SELECT DISTINCT CUSTOMER_ID,COLLATERAL_ID FROM COLLATERAL
			WHERE REPORT_DATE = @REPORT_DT
		) X 
		GROUP BY COLLATERAL_ID
		HAVING COUNT(1)>1
) COL
	ON COL.COLLATERAL_ID = RESULT_COLLATERAL


--DELETE EXISTING DATA BY REPORT DATE
DELETE FROM DBO.COLLATERAL_CREDIT_COMMITED
WHERE REPORT_DT = @EOM_DT

--INSERT NEW DATA BY REPORT DATE
INSERT INTO [dbo].[COLLATERAL_CREDIT_COMMITED] (
		[REPORT_DT]
		,[COLLATERAL_NO]
		,[NO_REKENING]
		,[NILAI_AG]
		,[NILAI_AG_DIPERHITUNGKAN]
		,[NILAI_AG_DIPERHIUTNGKAN_KT]
		,[BRANCH]
		,[RG_BRANCH]
)
SELECT  
		@EOM_DT AS REPORT_DT,			
		COLLATERAL_NO,	
		NO_REK,	
		try_convert( numeric( 24,2), FORMAT( TRY_CONVERT( numeric( 38,8), COLLATERAL_AMOUNT_RESULT ), '#.00') ) as COLLATERAL_AMOUNT_RESULT, 
		try_convert( numeric( 24,2), FORMAT( TRY_CONVERT( numeric( 38,8), CREDIT_RESULT), '#.00')) as CREDIT_RESULT,
		try_convert( numeric( 24,2), FORMAT( TRY_CONVERT( numeric( 38,8), LENIENCY_RESULT), '#.00')) as LENIENCY_RESULT
		,[BRANCH]
		,[RG_BRANCH]
FROM @Loan

SELECT 
	@EOM_DT AS REPORT_DT,
    [BRANCH],
	[RG_BRANCH],
	[ID_OPRSNL],
	ACCOUNT_NO,
	[COLLATERAL_NO],
	[ID_DBTUR],
	[CHARACTER],
	[INITIAL_AGREEMENT_NO],
	[INITIAL_AGREEMENT_DATE],
	[LAST_AGREEMENT_NO],
	[LAST__AGREEMENT_DATE],
	[NITIAL_DATE],
	[START_DATE],
	[LAST_DATE],
	[DEBTOR_CATEGORY],
	[PORTOFOLIO_CATEGORY],
	[CHARACTER2],
	CREDIT_ORIENTATION,
	CURRENCY,
	CLASSIFICATION_ASSET,
	CREDIT_DESC,
	SECTOR_CREDIT,
	ECONOMY_SECTOR,
	PROJECT_LOCATION,
	MAIN_RATE_DESC,
	MAIN_RATE,
	QUALITY,
	MAIN_PLAFOND,
	PLAFOND,
	TOTAL_DBT,
	DEBIT_MOVEMENT,
	FACILITY_IN_RATE,
	COLLATERAL_AMOUNT_RESULT,
	COMMITED_IDR,
	UNUSED_IDR,
	COLLATERAL_AMOUNT_RESULT,
	SUM( CREDIT_RESULT) as CREDIT_RESULT,
	SUM( LENIENCY_RESULT) as LENIENCY_RESULT

FROM @Loan
group by
	[BRANCH],
	[RG_BRANCH],
	[ID_OPRSNL],
	ACCOUNT_NO,
	[COLLATERAL_NO],
	[ID_DBTUR],
	[CHARACTER],
	[INITIAL_AGREEMENT_NO],
	[INITIAL_AGREEMENT_DATE],
	[LAST_AGREEMENT_NO],
	[LAST__AGREEMENT_DATE],
	[NITIAL_DATE],
	[START_DATE],
	[LAST_DATE],
	[DEBTOR_CATEGORY],
	[PORTOFOLIO_CATEGORY],
	[CHARACTER2],
	CREDIT_ORIENTATION,
	CURRENCY,
	CLASSIFICATION_ASSET,
	CREDIT_DESC,
	SECTOR_CREDIT,
	ECONOMY_SECTOR,
	PROJECT_LOCATION,
	MAIN_RATE_DESC,
	MAIN_RATE,
	QUALITY,
	MAIN_PLAFOND,
	PLAFOND,
	TOTAL_DBT,
	DEBIT_MOVEMENT,
	FACILITY_IN_RATE,
	COLLATERAL_AMOUNT_RESULT,
	COMMITED_IDR,
	UNUSED_IDR,
	COLLATERAL_AMOUNT_RESULT,
	[CREDIT_RESULT],
	[LENIENCY_RESULT]

	SET NOCOUNT OFF;
RETURN

END
